FROM frankhinek/tensorflow:gpu

LABEL maintainer="Frank Hinek <frank.hinek@gmail.com>"

ARG keras_version=2.1.2

# Install Keras with default TensorFlow backend
RUN pip --no-cache-dir install keras==${keras_version}
